In [1]:
import pandas as pd
## StringIo basically turns the string into something that behaves like a file
from io import StringIO 
Data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
df=pd.read_json(StringIO(Data))

In [2]:
df

,employee_name,email,job_profile
0,James,james@gmail.com,"{'title1': 'Team Lead', 'title2': 'Sr. Develop..."

In [3]:

df.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [4]:

df.to_json(orient='index')

'{"0":{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [5]:

df.to_json(orient='records')

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [6]:
df=pd.read_csv("https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data",header=None)

In [7]:
df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1,14.23,1.71,2.43,15.6,127,2.80,3.06,0.28,2.29,5.64,1.04,3.92,1065
1,1,13.20,1.78,2.14,11.2,100,2.65,2.76,0.26,1.28,4.38,1.05,3.40,1050
2,1,13.16,2.36,2.67,18.6,101,2.80,3.24,0.30,2.81,5.68,1.03,3.17,1185
3,1,14.37,1.95,2.50,16.8,113,3.85,3.49,0.24,2.18,7.80,0.86,3.45,1480
4,1,13.24,2.59,2.87,21.0,118,2.80,2.69,0.39,1.82,4.32,1.04,2.93,735

In [8]:

df.to_csv("wine.csv")

In [9]:
url="https://www.fdic.gov/resources/resolutions/bank-failures/failed-bank-list/"

df=pd.read_html(url)

In [10]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Tioga-Franklin Savings Bank,Philadelphia,Pennsylvania,33802,Second Federal Savings and Loan Association of...,"August 21, 2026",10554
1,Small Business Bank,Lenexa,Kansas,25744,"The Farmers State Bank of Oakley, Kansas","July 17, 2026",10553
2,Kentland Federal Savings and Loan Association,Kentland,Indiana,28722,Kentland Bank,"July 10, 2026",10552
3,Community Bank and Trust - West Georgia,LaGrange,Georgia,25796,Anchor Bank,"May 1, 2026",10551
4,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
5,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
6,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
7,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
8,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
9,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
10,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
11,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
12,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
13,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
14,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
15,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
16,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
17,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
18,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
19,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
20,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
21,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
22,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
23,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
24,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528

In [11]:
!pip install lxml
!pip install html5lib
!pip install beautifulsoup4

Requirement already satisfied: lxml in c:\users\hp\appdata\roaming\python\python313\site-packages (6.1.0)
Requirement already satisfied: html5lib in c:\users\hp\miniconda3\lib\site-packages (1.1)
Requirement already satisfied: six>=1.9 in c:\users\hp\appdata\roaming\python\python313\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in c:\users\hp\miniconda3\lib\site-packages (from html5lib) (0.5.1)
Requirement already satisfied: beautifulsoup4 in c:\users\hp\appdata\roaming\python\python313\site-packages (4.14.3)
Requirement already satisfied: soupsieve>=1.6.1 in c:\users\hp\appdata\roaming\python\python313\site-packages (from beautifulsoup4) (2.8.3)
Requirement already satisfied: typing-extensions>=4.0.0 in c:\users\hp\appdata\roaming\python\python313\site-packages (from beautifulsoup4) (4.15.0)

In [12]:

url="https://www.boxofficemojo.com/year/world/"
pd.read_html(url,match="Worldwide",header=0)[0]

,Rank,Release Group,Worldwide,Domestic,%,Foreign,%.1
0,1,Spider-Man: Brand New Day,"$2,219,901,181","$854,901,181",38.5%,"$1,365,000,000",61.5%
1,2,The Odyssey,"$1,448,194,630","$539,269,630",37.2%,"$908,925,000",62.8%
2,3,Toy Story 5,"$1,128,578,473","$477,927,473",42.3%,"$650,651,000",57.7%
3,4,Michael,"$1,016,068,388","$372,303,388",36.6%,"$643,765,000",63.4%
4,5,The Super Mario Galaxy Movie,"$1,013,045,939","$429,814,610",42.4%,"$583,231,329",57.6%
...,...,...,...,...,...,...,...
195,196,Is God Is,"$4,945,741","$4,945,741",100%,-,-
196,197,Bhooth Bangla,"$4,912,634","$2,168,456",44.1%,"$2,744,178",55.9%
197,198,Harika Kanatlar: Okyanusun Merkezine Yolculuk,"$4,876,079",-,-,"$4,876,079",100%
198,199,Blood Paradise,"$4,856,164",-,-,"$4,856,164",100%
199,200,BTS WORLD TOUR 'ARIRANG' in JAPAN: LIVE VIEWING,"$4,839,090","$1,800,000",37.2%,"$3,039,090",62.8%

In [13]:

!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\hp\appdata\roaming\python\python313\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\hp\appdata\roaming\python\python313\site-packages (from openpyxl) (2.0.0)

In [14]:
df_excel=pd.read_excel('data.xlsx')
df_excel.to_pickle('df_excel')

In [15]:

pd.read_pickle('df_excel')

    Name  Age
0  Krish   32
1   Jack   34
2   John   31